### ISSUE TITLE
Feature Request Attaching

### ISSUE THREAD

**Issue by djdanby** [TobiasF92/FS22_interactiveControl#10]
Is there any way to add a attacherjoint attach/detach function? Most tractors have a lever for attaching and detaching the trailer or implement. Would be cool. :)

And a color change function too. When you look at a trigger point, which then changes the color of the trigger. With this you could design nicer trigger areas and do without the overlapping trigger icons.

**Comment by TobiasF92** [comment]
Will be added in the next version: `ATTACHERJOINTS_ATTACH_DETACH`
