### ISSUE TITLE
Folding bug in multiplayer mode

### ISSUE THREAD

**Issue by HatsuneKid** [TobiasF92/FS22_interactiveControl#11]
A vehicle and a trailer I've add Interactive Control function to their foldable part. So that I can directly control their foldable parts through IC button. They both work fine in single player mode without any error.

`

    <interactiveControl>
        <interactiveControlConfigurations title="$l10n_actionIC_Animation">
            <interactiveControlConfiguration name="$l10n_actionIC_IC">
                <interactiveControls>
                    <outdoorTrigger node="0>1|0" />
                    <interactiveControl posText="$l10n_foldCrane" negText="$l10n_unfoldCrane" >
                        <clickPoint node="0>0|12|4|6" size="0.1" type="OUTDOOR" iconType="UNFOLD1" alignToCamera="false"/>
                        <function name="FOLDING_TOGGLE"/>
                    </interactiveControl>
                </interactiveControls>
            </interactiveControlConfiguration>
        </interactiveControlConfigurations>
        <registers>
            <clickIcon filename="shared/IC_icons/ic_clickIcon.i3d" name="UNFOLD1" node="13"/>
        </registers>
    </interactiveControl>
    <foldable>
        <foldingConfigurations>
            <foldingConfiguration>
                <foldingParts posDirectionText="$l10n_foldCrane" negDirectionText="$l10n_unfoldCrane" allowUnfoldingByAI="false">
                    <foldingPart animationName="folding" speedScale="1" />
                </foldingParts>
            </foldingConfiguration>
        </foldingConfigurations>
    </foldable>`

The problem is that in multiplayer mode, their foldable parts automatically unfold while other players join the game. How to solve this problem?

**Comment by HatsuneKid** [comment]
And how to add the control distance limit of IC button? Sometimes I want to open the tailgate, but I accidentally press the IC button on the cab door ten meters away from me.
And how to disable the invisible IC button? I want to make some complex component animations to make the IC button invisible and disable it.
Great thx

**Comment by TobiasF92** [comment]
Hey, I will take a look on the multiplayer bug, hope I can reproduce it.

You can use a distance refNode on buttons:
`<button ... range="5" refNode="node" />`
Range is the distance from the refNode. 5 Meters by default. refNode can be any node in your vehicle.

You can add depending animations in your buttons or clickPoints to hide them in some cases:
`<clickPoint/button ... animMaxLimit="1" animMinLimit="0" animName="string" />`

same for folding
`<clickPoint/button ... foldMaxLimit="1" foldMinLimit="0" />`

**Comment by HatsuneKid** [comment]
> Hey, I will take a look on the multiplayer bug, hope I can reproduce it.
> 
> You can use a distance refNode on buttons: `<button ... range="5" refNode="node" />` Range is the distance from the refNode. 5 Meters by default. refNode can be any node in your vehicle.
> 
> You can add depending animations in your buttons or clickPoints to hide them in some cases: `<clickPoint/button ... animMaxLimit="1" animMinLimit="0" animName="string" />`
> 
> same for folding `<clickPoint/button ... foldMaxLimit="1" foldMinLimit="0" />`

My fault, I should describe it as the range limit of the click point, not the button. I tried to add range limit of the click point but it didn't work.
About depending animations. I want to realize that when the left front curtain is opened, the click point of the left rear curtain will be invisible and invalid.
`

                     <interactiveControl posText="$l10n_actionIC_curtainClose" negText="$l10n_actionIC_curtainOpen" >
                        <clickPoint node="0>0|12|3|0" size="0.1" blinkSpeedScale="1.2" type="OUTDOOR" iconType="TURNLIGHT" alignToCamera="false" animMaxLimit="1" animMinLimit="0" animName="coverAnimationLeftBack"/>
                        <clickPoint node="0>0|12|3|0|0" size="0.1" blinkSpeedScale="1.2" type="OUTDOOR" iconType="TURNLIGHT" alignToCamera="false" animMaxLimit="1" animMinLimit="0" animName="coverAnimationLeftBack"/>
                        <animation name="coverAnimationLeftFront" speedScale="1.0" initTime="0.0"/>
                        <configurationsRestrictions>
                            <restriction name="design5" indicies="2 3" />
                        </configurationsRestrictions>
                    </interactiveControl>
                    <interactiveControl posText="$l10n_actionIC_curtainClose" negText="$l10n_actionIC_curtainOpen" >
                        <clickPoint node="0>0|12|3|1" size="0.1" blinkSpeedScale="1.2" type="OUTDOOR" iconType="TURNLIGHT" alignToCamera="false" animMaxLimit="1" animMinLimit="0" animName="coverAnimationLeftFront"/>
                        <clickPoint node="0>0|12|3|1|0" size="0.1" blinkSpeedScale="1.2" type="OUTDOOR" iconType="TURNLIGHT" alignToCamera="false" animMaxLimit="1" animMinLimit="0" animName="coverAnimationLeftFront"/>
                        <animation name="coverAnimationLeftBack" speedScale="1.0" initTime="0.0"/>
                        <configurationsRestrictions>
                            <restriction name="design5" indicies="2 3" />
                        </configurationsRestrictions>
                    </interactiveControl>
`
But those click points of the two animations still work independently. Log is clean and mod version 1.1.0.0-beta2. Is there something wrong in my code?

**Comment by TobiasF92** [comment]
Range of clickpoint is currently not implemented. 

You have to adjust the min and max Limits of the Animation. If you use 0 to 1 the clickpoint is always active

**Comment by HatsuneKid** [comment]
> Range of clickpoint is currently not implemented.
> 
> You have to adjust the min and max Limits of the Animation. If you use 0 to 1 the clickpoint is always active

Done! max0.1 to min0 work fine.
How about dependingInteractiveControl, can it achieve the same function?
`                    <dependingInteractiveControl index="int" blockState="boolean" forcedBlockedState="boolean"/>`
I tried to add it in my code and it work but its effect is not what I expected. I don't know what parameters I should fill in blockState and forcedBlockedState.

**Comment by TobiasF92** [comment]
blockState: Control state to block depending control
forcedBlockedState: Forced state of depending control if blocked

**Comment by TobiasF92** [comment]
> The problem is that in multiplayer mode, their foldable parts automatically unfold while other players join the game. How to solve this problem?

Can you retest this with current Beta2 Version? 
https://github.com/TobiasF92/FS22_interactiveControl/releases/tag/1.1.0.0-beta2

**Comment by HatsuneKid** [comment]
> > The problem is that in multiplayer mode, their foldable parts automatically unfold while other players join the game. How to solve this problem?
> 
> Can you retest this with current Beta2 Version? https://github.com/TobiasF92/FS22_interactiveControl/releases/tag/1.1.0.0-beta2

New version still has the same problem in multiplayer mode.
Testing in new savegame just with my trailer and interactiveControl. When my friend joined the game, He saw a game prompt immediately. It said that you must start the engine before folding the vehicle. And I knew that comes from my hook lift trailer with IC function of FOLDING_TOGGLE. There are no related errors recorded in the game log.
It seems that in multiplayer mode, the behavior of other players joining the game will trigger the folding function with interactiveControl.
Good news is CRABSTEERING_TOGGLE and ATTACHERJOINTS_TOGGLE_DISCHARGE seem to be work fine in multiplayer mode at present. A small proposal is to make CRABSTEERING_TOGGLE work like FOLDING_TOGGLE only after the player starts the engine.

**Comment by TobiasF92** [comment]
The folding bug should be fixed in [Beta3](https://github.com/TobiasF92/FS22_interactiveControl/releases/tag/1.1.0.0-beta3)

**Comment by HatsuneKid** [comment]
Bug fixed, nice~
