### ISSUE TITLE
Weird orange glow

### ISSUE THREAD

**Issue by cwhandersen** [TobiasF92/FS22_interactiveControl#16]
I tried modifying a base game telehandler to have interactive control.
And it works as it should without problems.

There is just a weird orange glow coming from the front of the vehicle. And I don't know why.
If I disable the interactive control mod, It disappears.
Any idea why this happens?

I linked a photo:
![2023-02-27 01_28_27-Greenshot](https://user-images.githubusercontent.com/92727147/221447159-8bc575ed-25f8-4c2d-8ea6-94f80fba1da1.png)

**Comment by TobiasF92** [comment]
It seems to be triggered by a beaconlight. I am pretty sure that this is not caused by IC 🤔 
Try to take a look into your beacons

**Comment by cwhandersen** [comment]
I fixed it. Thanks for the help.
It was apparently the way the game loads beacon lights
