### ISSUE TITLE
Eigentlich kein Problem eher eine Frage.

### ISSUE THREAD

**Issue by FarmerMike87** [TobiasF92/FS22_interactiveControl#18]
Erstmal vielen Dank für dieses Script, geniale Arbeit wie man es vom gesammten Vertex Team ja gewohnt ist.

Nun zu meiner Frage is es möglich iwo einen Eintrag zu ändern, damit die Marker dauerhaft sichtbar bleiben ?? Wenn ja wo?
Ich hab mir die Script schon angesehen nur hab ich nix finden können, das ich das hätte vllt selbst ändern können.

In diesem Sinne vielen Dank im vorraus.

**Comment by TobiasF92** [comment]
In [Beta3](https://github.com/TobiasF92/FS22_interactiveControl/releases/tag/1.1.0.0-beta3) ist unter den Spieloptionen ein neues Feld mit Einstellungsmöglichkeiten hinzugefügt worden. Damit kannst du IC dauerhaft einschalten
