### ISSUE TITLE
Select vehicle

### ISSUE THREAD

**Issue by Michaelj15** [TobiasF92/FS22_interactiveControl#29]
Hello Tobias,

I asked a few weeks/ months ago, but i can't find my question anymore. 
Did you know or find already a solution for activating interactive control when a implement is selected?
In my case, IC only could be activated when the tractor is selected with the G key. When a front or back implement is selected, the IC won't be activated.

**Comment by TobiasF92** [comment]
Thats something I cant reproduce. I never use any restrictions for implement/tractor selection
