### ISSUE TITLE
Localisation for Italian and Russian speaker

### ISSUE THREAD

**Issue by Rudolfet** [TobiasF92/FS22_interactiveControl#3]
Hello,

i have localized for the italian gaemer for FS22/LS22.

Thanks.
[locale_it.zip](https://github.com/TobiasF92/FS22_interactiveControl/files/10047508/locale_it.zip)

**Comment by razormoddingteam** [comment]
I join the discussion. Here is the localization for Russian speakers, thank you!
[locale_ru.zip](https://github.com/TobiasF92/FS22_interactiveControl/files/10048294/locale_ru.zip)

**Comment by TobiasF92** [comment]
Thank both of you for your work!
