### ISSUE TITLE
Some functions do not work

### ISSUE THREAD

**Issue by Kalderone** [TobiasF92/FS22_interactiveControl#30]
Good day! I wanted to include the following functions in the combine 
ATTACHERJOINT_LIFT_LOWER
ATTACHERJOINT_FOLDING_TOGGLE

But no matter how hard I tried, they do not work on the combine.

I downloaded a recent mod of the combine from the modhub where the ATTACHERJOINT_LIFT_LOWER function is also implemented
https://www.farming-simulator.com/mod.php?lang=en&country=ua&mod_id=267177&title=fs2022

But this combine with the ATTACHERJOINT_LIFT_LOWER function also does not work for me. Maybe the problem is in the scripts or something else?

**Comment by TobiasF92** [comment]
![fsScreen_2023_05_18_12_38_13](https://github.com/TobiasF92/FS22_interactiveControl/assets/84439060/48c5cce1-8f35-4131-963f-3d60d51e52fb)

Are you using the last release of InteractiveControl?
For me everything on this mod is working.

**Comment by Kalderone** [comment]
Hello! I found out the problem, I have a conflict with the Tool Height Control For Headers mod
