### ISSUE TITLE
No issui, just a question

### ISSUE THREAD

**Issue by Michaelj15** [TobiasF92/FS22_interactiveControl#33]
Hi Tobias, 
I have a question for the interactive xml editing. 
I working on an animation for a baler. 
With interactive control there is a chamber who loads a visual netwrole into the baler. 
This works fine, but interactive control roles back the animation lines in the xml. 
So when closing the chamber, the netwrole comes visible again when clicking again on the interactive control button. 
Is there a xml editing line to click only one time on the interactive control button? 
Or do i need something change in the animation section? 

So summarized what i wish, the netwrole goes visible into the baler when clicking the IC point. 
Clicking again on the IC point, the animation starts again and not backwards.

**Comment by TobiasF92** [comment]
Hi, think thats not possible atm 🤔
