### ISSUE TITLE
[Enhancement] Translation PT-BR

### ISSUE THREAD

**Issue by Myiamoto86** [TobiasF92/FS22_interactiveControl#35]
Dear,

I hereby contribute to your work and provide the PT-BR translation I made for myself. It is already tested and functional.

Any other support you need for translation of mods, I will be available.

Cheers
[locale_br.txt](https://github.com/TobiasF92/FS22_interactiveControl/files/12009152/locale_br.txt)

**Comment by TobiasF92** [comment]
Thank you, I will add it to a feature release :)
