### ISSUE TITLE
No separation of raise/lower functions and other functions

### ISSUE THREAD

**Issue by razormoddingteam** [TobiasF92/FS22_interactiveControl#4]
Good afternoon or evening. I wanted to animate the levers on my tractor to raise and lower the equipment. 

The lever has three positions **(-15; 0; 0) (0; 0; 0) (15; 0; 0)** But alas, it did not work out, from the tests I realized that the animation works only once. The second time it will not work to start until the attacherjoint lift or lower again. 

Is it possible to start another animation in the opposite direction, for example, when lowering the attacherjoint **(0; 0; 0) --> (-15; 0; 0)**, and when raising **(0; 0; 0) --> (15; 0; 0)** ???

**_Thanks for the script and in advance for answering my question!_**

**Comment by TobiasF92** [comment]
Hey, 

you can use a dashboard entry to achive the expected result:

```
<dashboard displayType="ROT" node="Joystick" minRot="0 -0.06 0" maxRot="0 -0.06 15"  raiseTime="0.25" activeTime="0.05" valueType="ic_action" onICActivate="true" onICDeactivate="false"/>
<dashboard displayType="ROT" node="Joystick" minRot="0 -0.06 0" maxRot="0 -0.06 -15" raiseTime="0.25" activeTime="0.05" valueType="ic_action" onICActivate="false" onICDeactivate="true"/>
```

**Comment by razormoddingteam** [comment]
> Hey,
> 
> you can use a dashboard entry to achive the expected result:
> 
> ```
> <dashboard displayType="ROT" node="Joystick" minRot="0 -0.06 0" maxRot="0 -0.06 15"  raiseTime="0.25" activeTime="0.05" valueType="ic_action" onICActivate="true" onICDeactivate="false"/>
> <dashboard displayType="ROT" node="Joystick" minRot="0 -0.06 0" maxRot="0 -0.06 -15" raiseTime="0.25" activeTime="0.05" valueType="ic_action" onICActivate="false" onICDeactivate="true"/>
> ```
Oh, thank you, I just now got it.
I studied the mod at night, apparently I didn't understand a little
