### ISSUE TITLE
Hupe per click icon auslösen

### ISSUE THREAD

**Issue by hleithoff** [TobiasF92/FS22_interactiveControl#44]
Hallo .... Ich habe merfach vergeblich versucht die Hupe  (Honk event) per clickitem auszulösen.
leider bisher ohne Erfolg ....
Könnte mir jemand da behilflich sein ?

<function name="Honk"/>     klappt leider nicht.
<function name="Honk_event"/>    klappt leider nicht.

Vielen Dank.
Gruß H.Leithoff

**Comment by TobiasF92** [comment]
Hallo, es ist momentan nicht möglich die Hupe mit IC zu bedienen.
