### ISSUE TITLE
IC errors in log

### ISSUE THREAD

**Issue by MX5Marc** [TobiasF92/FS22_interactiveControl#59]
I've tried to add an IC control for the Front/Back Diff Lock, and AWD.  The log is giving me the following error:

`Loaded interactive control does not allow saving 'vehicles.vehicle(22).FS22_interactiveControl.interactiveControl.control(14)', skipping this control`

This is my entry in the xml:
'<interactiveControl posText="$l10n_actionIC_frontDiffLock_toggle" negText="$l10n_actionIC_frontDiffLock_toggle">
            <clickPoint node="interactiveControlFDL" size="0.05" type="INDOOR" iconType="CROSS" />
            <function name="VCA_TOGGLE_DIFFLOCK_FRONT" />
          </interactiveControl>
		  
		  <interactiveControl posText="$l10n_actionIC_backDiffLock_toggle" negText="$l10n_actionIC_backDiffLock_toggle">
            <clickPoint node="interactiveControlBDL" size="0.05" type="INDOOR" iconType="CROSS" />
            <function name="VCA_TOGGLE_DIFFLOCK_BACK" />
          </interactiveControl>
		  
		  <interactiveControl posText="$l10n_actionIC_AWD_toggle" negText="$l10n_actionIC_AWD_toggle">
            <clickPoint node="interactiveControlAWD" size="0.05" type="INDOOR" iconType="CROSS" />
            <function name="VCA_TOGGLE_AWD" />
          </interactiveControl> `

The entries exist in the ModDesc, and nodes are set in the 13d mappings
What have I done wrong please?
Thanks

**Comment by TobiasF92** [comment]
Thats no error, it's a warning ;)

You edited a vehicle and used an existing savegame, so the order of loaded controls doesnt match to the vehicle config.

This warning wont show up again, after you save your game.
