### ISSUE TITLE
LUA call stack

### ISSUE THREAD

**Issue by FirenzeIT** [TobiasF92/FS22_interactiveControl#65]
Hello, i have this type of LUA call stack from version downloaded here on github (also with modhub version):

2024-06-28 01:50 LUA call stack:
  dataS/scripts/i3d/I3DUtil.lua (20) : printCallstack
  dataS/scripts/i3d/I3DUtil.lua (91) : checkChildIndex
  dataS/scripts/xml/XMLValueType.lua (61) : indexToObject
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/interactiveControl/InteractiveClickPoint.lua (115) : getValue
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (360) : loadFromXML
  dataS/scripts/xml/XMLFile.lua (296) : closure
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (357) : iterate
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (218) : loadInteractiveControlFromXML
  dataS/scripts/xml/XMLFile.lua (296) : closure
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (215) : iterate
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (993) : raiseEvent
  dataS/scripts/i3d/I3DManager.lua (134) : asyncCallbackFunction
2024-06-28 01:50 2024-06-28 01:50   Error: Index not found: 0>0|8|6|12|5C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/data/shared/ic_clickIcons.i3d (3.34 ms)

2024-06-28 01:50   Error: Failed to find child 19 from node visuals, only 17 children given
2024-06-28 01:50 LUA call stack:
  dataS/scripts/i3d/I3DUtil.lua (20) : printCallstack
  dataS/scripts/i3d/I3DUtil.lua (91) : checkChildIndex
  dataS/scripts/xml/XMLValueType.lua (61) : indexToObject
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/interactiveControl/InteractiveClickPoint.lua (115) : getValue
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (360) : loadFromXML
  dataS/scripts/xml/XMLFile.lua (296) : closure
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (357) : iterate
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (218) : loadInteractiveControlFromXML
  dataS/scripts/xml/XMLFile.lua (296) : closure
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (215) : iterate
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (993) : raiseEvent
  dataS/scripts/i3d/I3DManager.lua (134) : asyncCallbackFunction
2024-06-28 01:50   Error: Index not found: 0>0|11|19|1
2024-06-28 01:50   Error: Failed to find child 19 from node visuals, only 17 children given
2024-06-28 01:50 LUA call stack:
  dataS/scripts/i3d/I3DUtil.lua (20) : printCallstack
  dataS/scripts/i3d/I3DUtil.lua (91) : checkChildIndex
  dataS/scripts/xml/XMLValueType.lua (61) : indexToObject
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/interactiveControl/InteractiveClickPoint.lua (115) : getValue
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (360) : loadFromXML
  dataS/scripts/xml/XMLFile.lua (296) : closure
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (357) : iterate
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (218) : loadInteractiveControlFromXML
  dataS/scripts/xml/XMLFile.lua (296) : closure
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_interactiveControl/src/vehicles/specializations/InteractiveControl.lua (215) : iterate
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (993) : raiseEvent
  dataS/scripts/i3d/I3DManager.lua (134) : asyncCallbackFunction
2024-06-28 01:50   Error: Index not found: 0>0|11|19|0
2024-06-28 01:50   Error: Failed to find child 12 from node cabin_vis, only 12 children given

**Comment by TobiasF92** [comment]
`2024-06-28 01:50 Error: Index not found: 0>0|8|6|12|5
2024-06-28 01:50 Error: Index not found: 0>0|11|19|1
2024-06-28 01:50 Error: Index not found: 0>0|11|19|0`

Thats not a bug from IC, some of your indices are invalid
