### ISSUE TITLE
mod doen't shows up in game

### ISSUE THREAD

**Issue by niesmieszek** [TobiasF92/FS22_interactiveControl#68]
Hi, i have problem with this mode saddly. I can see it when you enter to ,,downloadable content,, in my mods, but when im creating new save this mode doesn't shows up. I can't use it in any mode or anything. i tried reinstaling fs, trying to copy you ,,explained xml,, and still it doesn't work. Any solutions for this? Please help.

**Comment by TobiasF92** [comment]
So you can not select the mod in your mod selection screen before starting a savegame?

Please upload your logfile

**Comment by niesmieszek** [comment]
> So you can not select the mod in your mod selection screen before starting a savegame?
> Yes
> Please upload your logfile
Logfile form what? Sorry but im not really into this things. Can you explain please?
